### DISCUSSION TITLE
Some questions

### DISCUSSION THREAD

**Discussion by ZepsiZola** [froobynooby/FarmControl#49] [Q&A]
1. What is the difference between `remove-awareness` and `remove-random-movement`. I tried them both and it seems like it just made the animals in the farm stop moving. I wonder what `remove-awareness` does that is different to `remove-random-movement` in that case.

2. I want to trim vehicles in a certain area with this profile, but it says this in console when I try to enable it

profiles.yml 
```yaml
  # No more than 6 vehicles per area
  trim-vehicles:
    group:
      types:
        - "category:vehicle"
      count: 6
      distance: 8
    actions:
      - kill
```      
console
```> fc reload
[22:49:27 WARN]: [FarmControl] Note: action 'kill' in profile 'trim-vehicles' is incompatible with the following entity types: category:vehicle
[22:49:27 WARN]: [FarmControl] Unknown entity type 'type:monster' for profile 'disable-mob-collection-ai'.
[22:49:27 WARN]: [FarmControl] Reactive mode is not supported on your version - ignoring reactive profiles for world 'world'
[22:49:27 WARN]: [FarmControl] Reactive mode is not supported on your version - ignoring reactive profiles for world 'world_nether'
[22:49:27 WARN]: [FarmControl] Reactive mode is not supported on your version - ignoring reactive profiles for world 'world_the_end'
[22:49:27 INFO]: Plugin reloaded.
```

**Comment by froobynooby** [comment]
Hey - `remove-awareness` disables the entity's brain and pathfinder goals (mobs won't react to a player holding food, sheep won't eat grass, mobs won't attack players, etc) while `remove-random-movement` only disables the random movement pathfinder goals, which stops them from moving around but doesn't stop other important activities.

The kill action can only be applied to mobs (i.e. entities with health) - to remove vehicles you should use the `remove` action instead. The wiki page [here](https://github.com/froobynooby/FarmControl/wiki/Actions) tells you which actions apply to which entity types

**Reply by ZepsiZola** [reply]
What is the performance improvement difference between `remove-awareness` and `remove-random-movement`?
And now I have another question, if that's what `remove-awareness` does, then what does `remove-ai` do?

Also I had these settings and was still able to lure groups of animals toward me when they had `remove-awareness`. Except this time it took them a little longer to realise I was holding wheat.
profiles.yml
```yaml
profiles:
  # Remove random movements and disable collisions of mobs in animal farms
  soft-nerf-animal-farms:
    group:
      types:
        - "category:animal"
      count: 5
      distance: 6
      pure: true
    actions:
      - remove-random-movement
      - disable-collisions

  # Remove the awareness of mobs in animal farms
  hard-nerf-animal-farms:
    group:
      types:
        - "category:animal"
      count: 15
      distance: 6
      pure: true
    actions:
      - remove-awareness
      - disable-collisions
```

config.yml
```yaml
world-settings:
  default:
    profiles:
      proactive:
        - soft-nerf-animal-farms
        - hard-nerf-animal-farms

    action-settings:
      undo-on:
        default:
          interact: false
          damage: false
          target: false
          tempt: true
        remove-ai:
          interact: true
          damage: true
          target: true
        remove-awareness:
          interact: true
          damage: true
          target: true
        disable-collisions:
          tempt: true
        disable-breeding:
          interact: false
          tempt: false
