### ISSUE TITLE
cannot remove stacked mobs

### ISSUE THREAD

**Issue by hkkongou** [froobynooby/FarmControl#10]
paper 780 1.16.5
farmcontrol 1.1.8

Farm control cannot remove stacked mobs  in chunks with its profiler actions.

The following profiler works for removing excess vanilla mobs, but does not work on stackers mobs, i use wildstacker in my server.

```
  soft-nerf-animal-farms:
    group:
      types:
        - "category:animal"
        - villager
        - "category:monster"
      count: 4
      distance: same-chunk
    actions:
      - remove
```

video demonstration:
https://youtu.be/OwYIyJ7_xbw
