### ISSUE TITLE
Bats not being removed

### ISSUE THREAD

**Issue by srnyx** [froobynooby/FarmControl#12]
```yml
  bat:
    group:
      types:
        - "bat"
    actions:
      - remove
```
```yml
world-settings:
  default:
    profiles:
      proactive:
        - bat
```
But I still see bats flying around having a holly jolly time.
