### ISSUE TITLE
WolfControl

### ISSUE THREAD

**Issue by TomLewis** [froobynooby/FarmControl#17]
Another one from MFM:
Please add a way to limit Wolfs per person.
```
WolfControl:
  #  
  # Checks tamed wolfs in defined chunk range and if its above allowed limit then makes them sit down
  # This is limit per player so value of 2-3 is more than enough
  Enabled: true
  # Defines max allowed wolfs per player which can follow him
  # This will be checked on general entity amount check defined belove
  Max: 5
```
