### ISSUE TITLE
Entity types not working

### ISSUE THREAD

**Issue by stonegray** [froobynooby/FarmControl#3]
Certain entity types, such as `minecart` and `splash_potion`, don't work as expected and are being used to build lag machines. 

The [wiki for types](https://github.com/froobynooby/FarmControl/wiki/Groups#types) indicates that an entity is an accepted value. This works as expected for mobs, but fails for some [valid entities](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html), including:

- `splash_potion`
- `minecart` (and varients)

I've tried using both `kill` and `remove` actions, and using a working type such as `zombie` in the same group, which works as expected

**profiles.yml**
```yml
profiles:
  limit-minecarts:
    group:
      types:
        - "MINECART"
        - "SPLASH_POTION"
      count: 2
      distance: 20
    actions:
      - kill
```
**config.yml**
```yml
world-settings:
  default:
    profiles:
      proactive:
        - limit-minecarts
      reactive: []
...
```
