### ISSUE TITLE
Vehicle category is broken, entities stay there

### ISSUE THREAD

**Issue by pjindras** [froobynooby/FarmControl#64]
![Image](https://github.com/user-attachments/assets/12ce50c8-2329-41e9-8f2e-6d16344859aa)

Profile:

```
  trim-boat-chunks:
    group:
      types:
        - "category:vehicle"
      count: 64
      distance: 32
    actions:
      - remove

world-settings:
  default:
    # Which profiles (as given in profiles.yml) should we run?
    profiles:
      # These profiles are constantly run.
      proactive:
        - trim-boat-chunks
```
